#!/usr/local/bin/node

let fs = require('fs');
let Phrase = require('sshimizu-palindrome');

let text = fs.readFileSync('phrases.txt', 'utf-8');
detectedPalindromes = "";
text.split('\n').forEach(function(line){
  let phrase = new Phrase(line);
  if (phrase.palindrome()) {
    console.log('palindrome detected: ', line);
    detectedPalindromes += line + '\n';
  }
});

fs.writeFileSync('palindromes.txt', detectedPalindromes)
