#!/usr/local/bin/node

// Returns the paragraphs from a wikipedia link, stripped of reference numbers

let request = require('request');
let url = process.argv[2];

const jsdom = require('jsdom');
const { JSDOM } = jsdom;

console.log(url);
